### PR TITLE
Get HttpServletRequest from PolicyContext

### PR DESCRIPTION
**Pull request by ggam**
Replaces #220 with a more standard approach.

### CODE REVIEW

**Comment by arjantijms** [comment]
This is indeed the better solution, but I remember now why I used the HttpServletRequest from CDI. It's TomEE that has a bug or omission of some kind, where JACC works in EJBs, but not in Servlet.

See http://tomee-openejb.979440.n4.nabble.com/How-can-I-enable-JACC-in-TomEE-td4673113.html

Probably worth it to ask the TomEE people again. cc @jgallimore @jeanouii @rmannibucau

**Comment by arjantijms** [comment]
See this issue as well: https://issues.apache.org/jira/browse/TOMEE-1912

**Comment by ggam** [comment]
I'm right now looking at fixing TomEE tests and looking at that exact post
:)

I've found an interesting workaround using a Tomcat valve to register the
PolicyContextHandler (
https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-tomcat-integration/src/main/java/org/kie/integration/tomcat/JACCValve.java).
It's not pretty but I think it would work for us.

Regarding this particular PR, the fact is that TomEE will also fail to
retrieve the Subject from the PolicyContexy so I don't think we are any
better now. We can use the same workaround here.

**Comment by arjantijms** [comment]
>I'm right now looking at fixing TomEE tests and looking at that exact post
:)

Ah, ok ;)

>It's not pretty but I think it would work for us.

I briefly looked at that before. It's interesting that it isn't "real" JACC, but does provide some of the contexts making it perhaps good enough for now (it won't work with custom authorization modules if/when we come to that later).

More importantly, its existence does "prove" that there's a demand for JACC on Tomcat. I'd still like to see how hard it would be to port the Geronimo JACC code to a standalone Tomcat extension, and see if we can contribute that to Tomcat.

**Pull request merged**
