### PR TITLE
Fixed more TomEE tests

### PR DESCRIPTION
**Pull request by ggam**
Current failing tests:
- app-db
- app-mem-form
- app-mem-customform
- app-custom-session

~~Both `app-mem-form` and `app-mem-customform` might be due to a Tomcat bug. Tomcat saves some caller information only when JASPIC result is `SUCCESS`:
https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/authenticator/AuthenticatorBase.java#L798~~

~~Then, on logout, it only calls `ServerAuthModule#cleanSubject` when that data is present: https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/authenticator/AuthenticatorBase.java#L1139~~

~~That means `ServerAuthModule#cleanSubject` is not called on logout when the authentication result was `SEND_SUCCESS`, which is the case for redirects. I'll ask Tomcat developers or open a PR to take account of the SEND_SUCCESS result.~~

Additional notes: 
* This PR incorporates #223, which was needed for the custom-principal test.
* JACC tests will fail on Windows. I use a filesystem path for the JACC context id, which is different depending on the OS. I have to change it to always be Unix like (for now).
* I made some changes in CdiExtension. "this" was returning an unproxied object, which wasn't intercepted.
* Apparently, `tomee.additionalLibs` can only download from Maven Central. I tweaked the pom a bit.

### CODE REVIEW

**Comment by ggam** [comment]
Tomcat bug: https://bz.apache.org/bugzilla/show_bug.cgi?id=62547

For now the solution would be to provide a custom `NonLoginAuthenticator` (https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/authenticator/NonLoginAuthenticator.java) that overrides `AuthenticatorBase#authenticateJaspic` fixing its behavior.

**Comment by ggam** [comment]
@arjantijms I created a PR for fixing Tomcat behavior at https://github.com/apache/tomcat/pull/116. While they review it, could you please upload a patched version of the jar to your repository? That way we can replace the module from TomEE

Here's the modified jar (just rename it to tomcat-catalina-8.5.20.jar) with the modified ``AuthenticatorBase.class`
[tomcat-catalina-8.5.20.jar.zip](https://github.com/eclipse-ee4j/soteria/files/2201415/tomcat-catalina-8.5.20.jar.zip)

**Comment by ggam** [comment]
All tests but `app-mem-basic-decorate` pass now on a local Windows machine.

**Comment by ggam** [comment]
Before merging this, I'll need the patched Catalina and the latest Jacc Provider version published on the usual repository. Would you please @arjantijms take care of it? @keilw may you please give be access to the BinTray repository so we can use it for future releases of these artifacts?

**Comment by ggam** [comment]
Great news: Tomcat accepted my PR fixing the bug that made the Catalina patch needed (https://github.com/apache/tomcat/pull/116). Next TomEE version will probably already incorporate it.

**Comment by arjantijms** [comment]
Great news! Shall we use the actual updated Catalina then instead of uploading a binary somewhere?

I guess there should be a nightly out soon then?

**Comment by keilw** [comment]
I created a new Bintray organization https://bintray.com/eclipse-ee4j, so let me know, if @ggam needed to update artifacts there. I already sent @arjantijms an invitation to join. However in this case, doesn't Apache also publish snapshots of Catalina somewhere?

**Comment by ggam** [comment]
Yes, Catalina snapshots are published at
https://repository.apache.org/content/repositories/snapshots/org/apache/tomcat/tomcat-catalina/8.5-SNAPSHOT/

I'll update this PR as soon as I can.

**Comment by keilw** [comment]
@ggam Was it updated already?

**Comment by ggam** [comment]
Now it is.

**Pull request merged**
