### PR TITLE
TomEE tests

### PR DESCRIPTION
**Pull request by ggam**
Currently this needs to have JACC TomEE bridge on the local repository, until it's pushed to the Payara Patched repository.

Some tests are failing:
* H2 database says credentials are invalid
* ~~More importantly, `HttpAuthenticationMechanism` selection doesn't work. OpenWebBeans tries to instantiate the mechanisms as if they were normal beans, instead of using the registered producers. I haven't looked more into it. @arjantijms perhaps you have some idea about this?~~
* securitycontext-customprincipal fails due to unrecognized container class. SubjectParser will probably need some tweaks

I've checked OpenLiberty tests, since it also uses OpenWebBeans, and they are failing at a previous point now. I'll fix them too in the following days.

### CODE REVIEW

**Comment by keilw** [comment]
Guess there's nobody from Tomitribe among possible reviewers?

**Comment by ggam** [comment]
> Guess there's nobody from Tomitribe among possible reviewers?

I don't think so: https://projects.eclipse.org/projects/ee4j.soteria/who

But you're right it's worth a try pining @dblevins or @rmannibucau

**Comment by arjantijms** [comment]
Hi,

Good thinking, hope one of them responds then.

**Comment by rmannibucau** [comment]
If it tries to instantate HttpAuthenticationMechanism it means the producer was not scanned (otherwise it would fail at startup) and that the HttpAuthenticationMechanism is a pojo instantiable. Check the exclusion list maybe (https://github.com/apache/tomee/blob/master/container/openejb-core/src/main/resources/default.exclusions - these are prefixes) or add in system.properties openejb.cdi.debug=true to see the found beans.

**Comment by ggam** [comment]
Thanks @rmannibucau, I'll have a deeper look this afternoon. The idea is that `BasicAuthenticationMechanism` (https://github.com/eclipse-ee4j/soteria/blob/master/impl/src/main/java/org/glassfish/soteria/mechanisms/BasicAuthenticationMechanism.java) is not scanned at deployment time (it doesn't contain any bean defining annotation, and the JAR doesn't have a `beans.xml` file), but it's dynamically added with a portable extension: https://github.com/eclipse-ee4j/soteria/blob/master/impl/src/main/java/org/glassfish/soteria/cdi/CdiExtension.java#L204

I'll try to ``@Veto` the beans and enable the mentioned property and give you more details if I can't find the issue. Thanks again!

**Comment by arjantijms** [comment]
I wonder if something changed recently in TomEE then, as at one point I think this was actually working (but tbh, it was a long time ago).

**Comment by rmannibucau** [comment]
We fixed some cdi issues but BasicAuthenticationMechanism shouldnt be identified as a bean cause of its constructor. It probably hides something else.

**Comment by ggam** [comment]
I just confirmed `BasicAuthenticationMechanism` is not being detected as a bean, but it's being added via the extension. The problem is CDI.current().select(HttpAuthenticationMechanism.class) tries to instantiate it via default constructor as if it were a normal bean. It doesn't work either with `@Inject`:

```
java.lang.NoSuchMethodException: org.glassfish.soteria.mechanisms.BasicAuthenticationMechanism.<init>()
	java.lang.Class.getConstructor0(Class.java:3082)
	java.lang.Class.getDeclaredConstructor(Class.java:2178)
	org.apache.webbeans.proxy.NormalScopeProxyFactory.createConstructor(NormalScopeProxyFactory.java:325)
	org.apache.webbeans.proxy.AbstractProxyFactory.generateProxy(AbstractProxyFactory.java:314)
	org.apache.webbeans.proxy.AbstractProxyFactory.createProxyClass(AbstractProxyFactory.java:241)
	org.apache.webbeans.proxy.AbstractProxyFactory.createProxyClass(AbstractProxyFactory.java:223)
	org.apache.webbeans.proxy.NormalScopeProxyFactory.createProxyClass(NormalScopeProxyFactory.java:271)
	org.apache.webbeans.proxy.NormalScopeProxyFactory.createProxyClass(NormalScopeProxyFactory.java:200)
	org.apache.webbeans.proxy.NormalScopeProxyFactory.createNormalScopeProxy(NormalScopeProxyFactory.java:149)
	org.apache.webbeans.container.BeanManagerImpl.getReference(BeanManagerImpl.java:777)
	org.apache.webbeans.container.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:673)
	org.apache.webbeans.inject.AbstractInjectable.inject(AbstractInjectable.java:103)
	org.apache.webbeans.inject.InjectableField.doInjection(InjectableField.java:65)
	org.apache.webbeans.portable.InjectionTargetImpl.injectFields(InjectionTargetImpl.java:220)
	org.apache.webbeans.portable.InjectionTargetImpl.inject(InjectionTargetImpl.java:206)
	org.apache.webbeans.portable.InjectionTargetImpl.inject(InjectionTargetImpl.java:196)
	org.apache.webbeans.component.AbstractOwbBean.create(AbstractOwbBean.java:126)
	org.apache.openejb.core.WebContext.newWeakableInstance(WebContext.java:153)
	org.apache.openejb.core.WebContext.newInstance(WebContext.java:181)
	org.apache.tomee.catalina.JavaeeInstanceManager.newInstance(JavaeeInstanceManager.java:78)
	org.apache.tomee.catalina.JavaeeInstanceManager.newInstance(JavaeeInstanceManager.java:124)
	org.apache.tomee.catalina.JavaeeInstanceManager.newInstance(JavaeeInstanceManager.java:119)
	org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:595)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)
```

**Comment by rmannibucau** [comment]
@ggam as expected and requested in the extension: https://github.com/eclipse-ee4j/soteria/blob/b4854a4051a45557f1804313d20ececdec4ab106/impl/src/main/java/org/glassfish/soteria/cdi/CdiExtension.java#L139

**Comment by ggam** [comment]
@rmannibucau but shouldn't it call the create method instead of defaulting to the no-args constructor?
https://github.com/eclipse-ee4j/soteria/blob/b4854a4051a45557f1804313d20ececdec4ab106/impl/src/main/java/org/glassfish/soteria/cdi/CdiExtension.java#L143

**Comment by rmannibucau** [comment]
@ggam it does but the scope requires a proxy so a nooarg constructor (can be protected). OWB supports all interceptors/proxying features whereas weld deactivate a few and require users to reimplement it in a custom manner. This is pby where the issue comes from.

**Comment by arjantijms** [comment]
@ggam Just to be sure, did you try if it fails in the same way with `FormAuthenticationMechanismDefinition`?

That one uses only the interfaces as bean type and types, see https://github.com/eclipse-ee4j/soteria/blob/b4854a4051a45557f1804313d20ececdec4ab106/impl/src/main/java/org/glassfish/soteria/cdi/CdiExtension.java#L154

Basic still had to be updated to be like that too, but I never got to it.

**Comment by ggam** [comment]
@rmannibucau wow thanks, just adding a protected no-args constructor made it work! Great to know we now rely on portable behavior.

@arjantijms those work since they have an (intrinsic) no-args constructor.

**Comment by arjantijms** [comment]
@ggam I've updated the JACC provider to 0.3 and deployed it to GitHub maven.

Is this PR ready to be merged?

**Comment by ggam** [comment]
@arjantijms there are still some failing tests, but I'll take care of them in the following days. One of them should get fixed once #223 is merged (SubjectParser fails to get the HttpServletRequest from CDI, don't know why), and the other is related to H2.

**Pull request merged**
