### PR TITLE
Openliberty test

### PR DESCRIPTION
**Pull request by ggam**
@arjantijms Here's OpenLiberty test target again. I had to make some tweaks to the server.xml

Surprisingly, tests are failing! 

I don't have time right now to look at it, but attached is the failsafe report from the only one that it tries to execute. Seems like a JACC issue.

I'll try to fix it when tomorrow.

[org.glassfish.soteria.test.AppSecurityContextIT.txt](https://github.com/eclipse-ee4j/soteria/files/2041504/org.glassfish.soteria.test.AppSecurityContextIT.txt)

### CODE REVIEW

**Comment by arjantijms** [comment]
That's 'correct', OpenLiberty supports JACC, but doesn't ship with a default JACC provider (which is a violation of the EE spec, but I think nobody ever challenged that).

There's two options:

1. Have the test install a simple default JACC provider.
2. Implement the SPI for Soteria (which we still have to add to Soteria), and use a Liberty specific way to get the roles from the security context.
3. Exclude the test that under the covers uses JACC for Liberty

p.s. TomEE fails for the same reason

**Comment by ggam** [comment]
I didn't remember these problems. For Liberty, I think the best solution is to just bundle a JACC provider. I doesn't seems fair to just skip some test when the tested funcionality won't work.

For that case, would you license your JACC provider under an Eclipse compatible text? It would be very useful so we just need to wrap it...... following the instructions from your blog.

TomEE only used JACC for EJBs and not Servlets IIRC? That would definitely be something to ask them for.

**Comment by arjantijms** [comment]
Hi,

Licensing the JACC provider under the Eclipse license is fine. It’s Apache
now.

So we “only” need to add Maven instructions to update the Open Liberty
server then,

One other approach is that I think the Liberty repo is open to third party
modules / features, so we could try to publish it there as well.

TomEE only indexes EJB security constraints following JACC indeed. The
Apache code for it is basically available already in the now defunct
Geronimo server. Since both Servlet and JACC barely changed there, I guess
it might still be useable.

Kind regards,
Arjan

**Comment by ggam** [comment]
I suspect there are some more problems with Liberty, probably JASPIC related.

On the app-securitycontext test, only two roles are on the ProtectionDomain after authentication, and none contains the roles:
jacc

**Comment by ggam** [comment]
Looking at it a little more, the Subject indeed contains the principals, but they are not accesible via `Subject#getPrincipals()` as they are "private credentials". The problem is on our SubjectParser which doesn't handle this situations.

**Comment by ggam** [comment]
Additionally, `JACC#getFromContext()` is returning null when `securityContext.isCallerInRole("foo")` is called.

**Comment by arjantijms** [comment]
>Looking at it a little more, the Subject indeed contains the principals, but they are not accesible via Subject#getPrincipals() as they are "private credentials". The problem is on our SubjectParser which doesn't handle this situations.

Interesting. Could be that Liberty changed something here between the time I originally tested it and today.

**Comment by ggam** [comment]
After a deeper look, seems like one more time, you already did my same finding long time ago:
```
// Liberty is the only known Java EE server that doesn't put the groups in
// the principals collection, but puts them in the credentials of a Subject.
// This somewhat peculiar decision means a JACC provider never gets to see
// groups via the principals that are passed in and must get them from
// the current Subject.

@SuppressWarnings("rawtypes")
Set<Hashtable> tables = subject.getPrivateCredentials(Hashtable.class);
if (tables != null && !tables.isEmpty()) {
    @SuppressWarnings("rawtypes")
    Hashtable table = tables.iterator().next();
    groups = (List<String>) table.get("com.ibm.wsspi.security.cred.groups");
}
```

That comment is on SubjectParser. I was about to ask you whether it was technically safe to get the Subject from the `ContextPolicy` on our `Policy` in order to parse the roles when I found it.

I guess that's the only way for Liberty. Do you think it's a viable solution?

**Comment by arjantijms** [comment]
Oh wow, almost had forgotten about that indeed, but yeah that's true.

The JACC spec should be transferred soon, so I wonder if we might be able to tighten up the specification then so that this peculiar workaround wouldn't be needed anymore.

**Comment by keilw** [comment]
Would this be part of EE4J or even Security Spec?

**Comment by arjantijms** [comment]
>JACC API has indeed been transferred today: https://github.com/eclipse-ee4j/jacc

oh wow :) I got a couple of notifications regarding the projects being created for staging and such, but didn't see the final thing yet. Cool!

>Callback establishing group principals within the argument subject.

There's a few troublesome statements like that indeed.

From what I understood, and Will kinda confirmed that with all the custom principal drama that we saw towards the end of EE Security 1.0, is that various vendors had started to use the Subject in such peculiar and unique ways that no spec could really say something about it. The Subject itself is a "bag of Principals and Credentials", but practically it's just an opaque black box.

So you need "adapter" readers and writers to get something in and out of that block box.

JASPIC is basically a writer. It hands the caller principal plus groups over to the container, and it "somehow" stores them in the Subject.

Then JACC, and that's the big missing piece still, didn't specify any way to read back the principals from a Subject. There isn't even really a way to get a group principal, since the higher level APIs only have tests for checking if the caller is in a certain role.

There might have been good reasons for this in the past (totally incompatible home-grown security systems that somehow had to be made compatible), but I think we can do better today.

**Comment by arjantijms** [comment]
>@arjantijms It's your show now ;-)

I'm not the only one, of course ;)

But that particular sentence was already non-portable. It basically said something like a vendor may opt to ignore the spec, but it must also be possible to configure the product to be spec compliant.

An alternative to that peculiar sentence might be to define exactly how this configuration to be spec compliant must be done, which was left out from the original wording.

**Comment by ggam** [comment]
Thanks for rebasing @arjantijms! I think I'll be able to continue working on this next week.

**Comment by arjantijms** [comment]
@ggam Can this be merged, or is more work needed as per your last comment?

**Comment by arjantijms** [comment]
@ggam I uploaded a version some time ago here:

https://github.com/payara/Payara_PatchedProjects/tree/eclipse

I used it myself too in a test, see here: https://github.com/javaee-samples/vendoree-samples/tree/master/payara/jacc-per-app

**Comment by ggam** [comment]
@arjantijms I also need the Liberty OSGi bundle. I have just made a (very ugly) workaround downloading and compiling the project

**Comment by arjantijms** [comment]
@ggam Okay, for the Liberty OSGi bundle we'll have to see what the best place to host it is. Not sure yet.

**Comment by keilw** [comment]
You mean a P2 bundle like Eclipse plugins? Or just OSGi enabling all the Maven artifacts, that should be easy, many JSRs like 363 or 354 did that, 382 also I think with Eclipse leading it.

**Comment by ggam** [comment]
@arjantijms doing a GitHub release containing the Liberty bundle and the `testjacc.mf` files would be enough I think. Once https://github.com/arjantijms/jacc-provider/pull/3 is merged, this will be ready to merge.

Some tests fail, since Liberty doesn't provide the `Subject` under `javax.security.auth.Subject.container` for unchecked calls, even when authentication was done and an identity has been stablished. I'll report the bug now.

I think we'll need IP approval for the added dependency. Another interesting approach, that we briefly discussed, is to move your JACC provider to the https://github.com/eclipse-ee4j/security-examples repository. Does anybody know whether we need IP approval *before* merging the PR, or is it just at release time?

@keilw the bundle I was talking about is https://github.com/arjantijms/jacc-provider/tree/master/liberty-bundle, which is needed for Liberty to enable JACC. Providing OSGi bundles for our artifacts would also be nice, specially now that OSGi is directly approaching CDI. I've just created a Bintray account with name "ggam" as here.

**Comment by ggam** [comment]
OpenLiberty issue: https://github.com/OpenLiberty/open-liberty/issues/4196

**Comment by arjantijms** [comment]
Hi,

Technically speaking the installation of the bundle would not be needed, as
Liberty claims to be Java EE compatible, and JACC requires a default
provider to be available.

So Liberty is not fully compatible.

**Comment by arjantijms** [comment]
>@arjantijms doing a GitHub release containing the Liberty bundle and the testjacc.mf files would be enough I think. 

I released 0.2 of the test JACC provider with the Liberty bundle.

See https://github.com/payara/Payara_PatchedProjects/tree/eclipse/org/omnifaces

**Comment by ggam** [comment]
Thanks! This is finished now. As I said, tests don't pass due to an OpenLiberty bug but our work is good to merge.

**Comment by arjantijms** [comment]
>but our work is good to merge.

Okay, perfect! Thanks :)

**Pull request merged**
