### PR TITLE
Jakarta EE namespace transition

### PR DESCRIPTION
**Pull request by jGauravGupta**
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

### CODE REVIEW

**Comment by rdebusscher** [comment]
Looks good.

There are a few other name changes required (like those for Jakarta Authorizaiton and Jakarta Authentication), but that can be done in another PR.

**Comment by arjantijms** [comment]
Thanks @jGauravGupta !

**Comment by keilw** [comment]
@arjantijms So this Jakarta spec will use "jakarta.security.enterprise", what about the other two raised e.g. by @thodorisbais?

**Comment by arjantijms** [comment]
@keilw 

This concerns the implementation. I wonder whether the artefact id should not just be "soteria" in stead of "jakarta.security.enterprise".

For the API though it should probably just be "jakarta.security". The "enterprise" part is unneeded. See here: https://github.com/eclipse-ee4j/security-api/blob/master/api/pom.xml#L30

**Comment by keilw** [comment]
Indeed, in the "impl" module "jakarta.security.enterprise" feels completely wrong, but I also spotted a few other problems, I'll raise a PR for that.
Regarding the API if we drop the "enterprise" that sounds fine, the question for all of them remains, if the Java packages of each API correspond with that groupId or not?

**Comment by arjantijms** [comment]
It’s a small pattern that made a little sense for the RIs in Java EE:

Javax.foo and Javax.foo-api

But even there it wasn’t done consistently. Updated Java packages can be considered for Jakarta EE 10 yes. A bunch of people also asked to make Authentication and Authorization sub-specs of Security, we might look into that too then.

**Comment by keilw** [comment]
If the refactoring doesn't break anything later in Jakarta EE 10, we might do  that later. Ideally the artifactId should only be changed once e.g. now after the specs got new names like "Authorization".

**Pull request merged**
