### PR TITLE
Synthetic CDI beans should have a beanClass attribute of the CDI extension

### PR DESCRIPTION
**Pull request by Skyllarr**
https://github.com/eclipse-ee4j/soteria/issues/337

@manovotn

### CODE REVIEW

**Comment by manovotn** [comment]
@Skyllarr thanks for sending the PR

**Review by manovotn — APPROVED** [review]

**Comment by Skyllarr** [comment]
@arjantijms Can you please review?

**Comment by arjantijms** [comment]
@Skyllarr sorry that this took so long, but it will through the cracks. Thanks for the PR!

**Review by arjantijms — APPROVED** [review]

**Comment by Skyllarr** [comment]
@arjantijms No problem, thank you! Is there an expected date for the release with this fix?

**Pull request merged**
