### PR TITLE
Addressing #214 Version number in POM?

### PR DESCRIPTION
**Pull request by keilw**
Signed-off-by: Werner Keil <werner.keil@gmx.net>

### CODE REVIEW

**Comment by keilw** [comment]
Again @arjantijms is somehow not available as reviewer. This also fixed his seemingly wrong username"atijmse7y" in the POM.

**Comment by arjantijms** [comment]
>Again @arjantijms is somehow not available as reviewer. This also fixed his seemingly wrong username"atijmse7y" in the POM.

Something apparently went wrong adding me, but @waynebeaton is on it.

atijms7y is unfortunately 'correct', it's my user name on Eclipse: 

https://accounts.eclipse.org/users/atijmse7y

I should perhaps try to get this adjusted. The issue is that I already had an ancient account on Eclipse (https://accounts.eclipse.org/users/atijms), to which I lost the password and is using an email of a company that doesn't even exist anymore.

**Comment by arjantijms** [comment]
p.s. the "1.1-b01" originated from the milestone builds that we did for Soteria before. As during the development we needed "stable" builds to push to Maven for people to test with.

Originally it was m01, m02, etc. But at some point Will thought Maven wasn't able to handle "m.." so he changed it to "b.." which he found Maven could handle.

**Comment by keilw** [comment]
Not sure, if it'll go into the actual version number, but the M1 tag seems to work for Eclipse projects, eventually we may face it here again.

**Pull request merged**
