### PR TITLE
Do not require a caller principal obtained from EJB to be assignable from CallerPrincipal

### PR DESCRIPTION
**Pull request by Skyllarr**
#343

### CODE REVIEW

**Comment by Skyllarr** [comment]
@arjantijms Can you please review? Thanks!

**Comment by arjantijms** [comment]
@Skyllarr unfortunately the ECA check keeps failing.

**Comment by Skyllarr** [comment]
@arjantijms Sorry about that. Seems that I did not have Eclipse Contributor Agreement accepted. It should hopefully pass now

**Comment by Skyllarr** [comment]
@arjantijms  ECA check is passing now

**Comment by Skyllarr** [comment]
Hello @arjantijms can you please review this one as well? ECA check is passing now

**Comment by arjantijms** [comment]
@Skyllarr sorry, this fell off the radar. I'll take a look at this issue (and several other open ones) soon.

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
