### PR TITLE
Deal with wrapped requests

### PR DESCRIPTION
**Pull request by ggam**
Requests might be wrapped and we can't know what version of it we'll get from CDI.

Payara updates the container Principal when the wrapped request overrides getUserPrincipal (https://github.com/payara/Payara/issues/2898) but @arjantijms I couldn't find a test for that on your "JASPIC TCK". I'd have to verify the spec and test other containers but I don't expect it to be mandated.

### CODE REVIEW

**Comment by arjantijms** [comment]
From a JASPIC point of view this wouldn't be really needed, since the HttpServletRequest#getUserPrincipal is already supposed to return the correct principal. The fix in Payara is basically an internal thing.

Nevertheless I think it wouldn't hurt to merge in, but the above should be kept in mind.

**Comment by ggam** [comment]
@arjantijms so JASPIC mandates wrapped requests to propagate the possibly changed Principal to the Subject?

If that's the case, we wouldn't need this PR, nor the vendor Principal checks, right? Since we only support HttpServlet requests (not remote EJBs or JAX-WS), we can take what we get from the request as "the truth" and only do vendor specific checks but for roles.

**Comment by arjantijms** [comment]
>@arjantijms so JASPIC mandates wrapped requests to propagate the possibly changed Principal to the Subject?

Well, if the request wrapping is internally done by the container, and the container's wrapped request would return a different or also wrapped Principal, then the (wrapped) `HttpServletRequest#getUserPrincipal` must return the `Principal` provided by a JASPIC SAM.

However, if a user wraps the request (say in a Servlet Filter), then there's no requirement that the result of calling `HttpServletRequest#getUserPrincipal` on that wrapped user provided request will somehow end up in the 'current' `Subject`.

**Comment by arjantijms** [comment]
@ggam What shall we do with this PR? Since the wrapping technically has to be done internally it's probably not needed, but what do you think?

**Comment by ggam** [comment]
I think this is good to have as a safeguard, but I haven't tested other servers. My point is that, in the hypothetic event that someone wraps the request and overrides the getUserPrincipal method, our `SecurityContext` *might* return an invalid result, since we don't really know what request is CDI providing to us.

It would be a strange case, but the fact that we have to rely on the request to get the caller principal instead of querying the Subject is also not ideal.

**Comment by arjantijms** [comment]
>It would be a strange case, but the fact that we have to rely on the request to get the caller principal instead of querying the Subject is also not ideal.

100% agree.

This is I think one of the key things we should address in the upcoming JACC/JASPIC/EE Security releases. It's not a "shiny" feature that will make headlines, but something that is very much needed.

If I'm not mistaken we had a short discussion about this earlier, where there's basically two options:

1. The caller Principal *MUST* be marked in some standard way in the principal. Discussed were having it implement an extra interface, putting it in a specially named Group, and a few other things which I forgot.

2. Reverse caller principal callbacks. The current ones essentially let one write a caller principal into the Subject. The reverse operation would allow us to get that same principal back. Might be a totally new interface or utility method, or an actual callback (but then we need a handler too).

**Comment by ggam** [comment]
Going a bit further, a better way to solve this is by getting the HttpServletRequest from the PolicyContext instead of CDI. The key `javax.servlet.http.HttpServletRequest` must return the original request that was used to provide authentication. My PR goes to the very original request without any wrappers. JACC will give a more precise view.

> If I'm not mistaken we had a short discussion about this earlier, where there's basically two options:
>    * The caller Principal MUST be marked in some standard way in the principal. Discussed were having it implement an extra interface, putting it in a specially named Group, and a few other things which I forgot.

How do you envision this to be backward compatible and totally portable? Adding another interface means only updated implementations will have it, while old authentication modules won't have it. It's even possible for the user now to register its own Principal from an HttpAuthenticationMechanism, which doesn't extend CallerPrincipal.

>    * Reverse caller principal callbacks. The current ones essentially let one write a caller principal into the Subject. The reverse operation would allow us to get that same principal back. Might be a totally new interface or utility method, or an actual callback (but then we need a handler too).

This seems more viable and in line with the rest of the JASPIC spec. Should also be easier to implement for vendors.

**Pull request closed without merging**
