### PR TITLE
Fixes #201

### LINKED ISSUE #201: Fix Readme
- [ ] The Readme still says Soteria is aiming at **EDR1**, can we please fix that and say it's final?!
- [ ] Readme also states: "There are 4 CI targets provided to test Soteria against: payara, wildfly, tomee", that is just 3 not 4 in that list.

### PR DESCRIPTION
**Pull request by ggam**
@arjantijms IIRC you had a setup for WebSphere Liberty that had to be removed due to licensing issues. Could we restore it for OpenLiberty?

Btw: you are not listed as a team member!

### CODE REVIEW

**Comment by ggam** [comment]
Thanks @ivargrimstad. I think this is a simple enough change to merge it without waiting for more reviews.
In order to do it in an Eclipse complaint way, should I "Create a merge commit" or "Squash and merge"?

**Comment by ivargrimstad** [comment]
@ggam I don't have a strong opinion, and I don't know if there is any Eclipse convention out there either, so just go with whatever you think is best.

**Comment by arjantijms** [comment]
> Could we restore it for OpenLiberty?

Yes, and for regular Liberty too. It's not really a licensing issue I think as it's a maven dependency that the user downloads and installs locally. The Maven plug-in and config is the same for both.

**Comment by arjantijms** [comment]
@ggam 
>Btw: you are not listed as a team member!

Hmmmm, how did you got listed?

**Comment by ggam** [comment]
Did you pay the fee? Haha.

Now seriously, I got added when my ECA was approved. I imagine that's a
manual process and as you had some issue with the configured email, they
probably forgot to finally add you...

**Comment by arjantijms** [comment]
@ggam 

I actually paid a fee, the Friends of Eclipse fee :P 

I've just mailed @waynebeaton about this, hope he can help.

**Comment by ggam** [comment]
So why it was actually removed? I recall there were some late problema but
don't remember the details.

Anyway Liberty now bundles its own JSR375 implementation so I'm not sure
it's worth ensuring compatibility with it.

Interestingly, RedHat chose Soteria as their implementation, at least for
now.

**Comment by ggam** [comment]
I just found the thread: https://javaee.groups.io/g/javaee-security-spec/topic/remove_liberty_support_from/12435811?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,12435811

I'll restore the target for OpenLiberty that already uses Eclipse license.

**Pull request merged**
